//UI STATE ACTION TYPES
export const INCREMENTER = 'INCREMENTER';

//AUTH STATE ACTION TYPES
export const LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
// export const AUTH_VERIFY = 'AUTH_VERIFY';
// export const AUTH_SET_SESSION = 'AUTH_SET_SESSION';
export const AUTH_IS_LOGGED_IN = 'AUTH_IS_LOGGED_IN';